// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NEZWalksAPI.Data;

#nullable disable

namespace NEZWalksAPI.Migrations
{
    [DbContext(typeof(NZWalksDbContext))]
    [Migration("20241112094804_Seeding Data for Difficulties and Region")]
    partial class SeedingDataforDifficultiesandRegion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NEZWalksAPI.Models.Domain.Difficulty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Difficulties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("df0d7d14-d835-46e8-9c54-76670ef57cef"),
                            Name = "Easy"
                        },
                        new
                        {
                            Id = new Guid("63f368c1-ff89-4f0a-88f6-f538ba89c229"),
                            Name = "Medium"
                        },
                        new
                        {
                            Id = new Guid("710fa13d-40e7-4694-8816-22944a1e4bd1"),
                            Name = "Hard"
                        });
                });

            modelBuilder.Entity("NEZWalksAPI.Models.Domain.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3a9f591c-7c9e-457c-87aa-766b8665b98c"),
                            Code = "Auk",
                            Name = "AuckLand",
                            RegionImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSgQt4gkKebi36jCQ6Bi1bVWYRybLEs-Vm2AA&s"
                        },
                        new
                        {
                            Id = new Guid("96e1007c-f6b5-43b2-bbd5-4f6cd679a107"),
                            Code = "06",
                            Name = "Gjilan",
                            RegionImageUrl = "https://kallxo.com/wp-content/uploads/2020/11/GJILANI-DRON-1-720x405.png"
                        },
                        new
                        {
                            Id = new Guid("d9fc392b-218a-4842-b6a5-1118af631336"),
                            Code = "01",
                            Name = "Prishtina",
                            RegionImageUrl = "https://www.albinfo.at/wp-content/uploads/2021/07/210644935_4230753403630675_6342664394500292046_n.jpg"
                        },
                        new
                        {
                            Id = new Guid("f97e90b4-6303-4da1-96f8-f2c850cbed97"),
                            Code = "02",
                            Name = "Mitrovice",
                            RegionImageUrl = "https://i0.wp.com/mytravelation.com/wp-content/uploads/2023/12/Mitrovica-Kosovo.jpg"
                        });
                });

            modelBuilder.Entity("NEZWalksAPI.Models.Domain.Walk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DifficultyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("LengthInKm")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WalkImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyId");

                    b.HasIndex("RegionId");

                    b.ToTable("Walk");
                });

            modelBuilder.Entity("NEZWalksAPI.Models.Domain.Walk", b =>
                {
                    b.HasOne("NEZWalksAPI.Models.Domain.Difficulty", "Difficulty")
                        .WithMany()
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NEZWalksAPI.Models.Domain.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Difficulty");

                    b.Navigation("Region");
                });
#pragma warning restore 612, 618
        }
    }
}
